### ISSUE TITLE
Action Blocked when tried to follow.

### ISSUE THREAD

**Issue by subhendukundu** [kaykyr/insta.js#3]
When I am trying to follow a user using the `/follow` API, throwing `This action was blocked. Please try again later. We restrict certain content and actions to protect our community. Tell us if you think we made a mistake.`. How do I fix this?

```
data: {
    message: 'feedback_required',
    spam: true,
    feedback_title: 'Action Blocked',
    feedback_message: 'This action was blocked. Please try again later. We ' +
      'restrict certain content and actions to protect our ' +
      'community. Tell us if you think we made a mistake.',
    feedback_url: 'repute/report_problem/instagram_follow_users/',
    status: 'fail'
  }
```

**Comment by kaykyr** [comment]
Hello! For this you need to use Mobile 4G proxies and reduce your activity speed.
